# Codespell configuration is within .codespellrc
---
name: Codespell

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "README-proxy.md"
      - "codex-rs/responses-api-proxy/README.md"
      - "codex-rs/responses-api-proxy/npm/README.md"
      - "codex-rs/responses-api-proxy/npm/package.json"
      - ".github/workflows/bazel.yml"
      - ".github/workflows/cargo-deny.yml"
      - ".github/workflows/ci.yml"
      - ".github/workflows/codespell.yml"
      - ".github/workflows/proxy-release.yml"
      - ".github/workflows/rust-ci.yml"
      - ".github/workflows/sdk.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "README-proxy.md"
      - "codex-rs/responses-api-proxy/README.md"
      - "codex-rs/responses-api-proxy/npm/README.md"
      - "codex-rs/responses-api-proxy/npm/package.json"
      - ".github/workflows/bazel.yml"
      - ".github/workflows/cargo-deny.yml"
      - ".github/workflows/ci.yml"
      - ".github/workflows/codespell.yml"
      - ".github/workflows/proxy-release.yml"
      - ".github/workflows/rust-ci.yml"
      - ".github/workflows/sdk.yml"

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Annotate locations with typos
        uses: codespell-project/codespell-problem-matcher@b80729f885d32f78a716c2f107b4db1025001c42 # v1
      - name: Codespell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          ignore_words_file: .codespellignore
